import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './e2e',
  timeout: 30000,
  retries: process.env.CI ? 2 : 1,
  reporter: [
    ['list'],
    ['html', { open: 'never', outputFolder: 'playwright-report' }],
  ],
  use: {
    baseURL: 'http://localhost:3001',
    screenshot: process.env.CI ? 'only-on-failure' : 'on',
    video: process.env.CI ? 'on-first-retry' : 'on',
    trace: process.env.CI ? 'on-first-retry' : 'on',
  },
  outputDir: 'test-results/artifacts',
  webServer: {
    command: process.platform === 'win32' ? 'set PORT=3001&& node dev-server.mjs' : 'PORT=3001 node dev-server.mjs',
    port: 3001,
    reuseExistingServer: true,
  },
  projects: [
    { name: 'core-ui', use: { browserName: 'chromium' }, testMatch: ['apiforge.spec.js'] },
    { name: 'user-scenarios', use: { browserName: 'chromium' }, testMatch: ['user-scenarios.spec.js'] },
    { name: 'json-editor', use: { browserName: 'chromium' }, testMatch: ['json-editor.spec.js'] },
    { name: 'query-params', use: { browserName: 'chromium' }, testMatch: ['query-params.spec.js'] },
    { name: 'body-types', use: { browserName: 'chromium' }, testMatch: ['body-types.spec.js'] },
    { name: 'examples', use: { browserName: 'chromium' }, testMatch: ['examples.spec.js'] },
    { name: 'request-tabs', use: { browserName: 'chromium' }, testMatch: ['request-tabs.spec.js'] },
    { name: 'schema-examples', use: { browserName: 'chromium' }, testMatch: ['schema-examples.spec.js'] },
    { name: 'source-traceability', use: { browserName: 'chromium' }, testMatch: ['source-traceability.spec.js'] },
    { name: 'save-as-doc', use: { browserName: 'chromium' }, testMatch: ['save-as-doc.spec.js'] },
    { name: 'docs-mode', use: { browserName: 'chromium' }, testMatch: ['docs-mode.spec.js'] },
    { name: 'openapi-responses', use: { browserName: 'chromium' }, testMatch: ['openapi-responses.spec.js'] },
    { name: 'response-insights', use: { browserName: 'chromium' }, testMatch: ['response-insights.spec.js'] },
    { name: 'search', use: { browserName: 'chromium' }, testMatch: ['search.spec.js'] },
    { name: 'themes', use: { browserName: 'chromium' }, testMatch: ['themes.spec.js'] },
    { name: 'env-variables', use: { browserName: 'chromium' }, testMatch: ['env-variables.spec.js'] },
    { name: 'curl-share', use: { browserName: 'chromium' }, testMatch: ['curl-share.spec.js'] },
    { name: 'auth', use: { browserName: 'chromium' }, testMatch: ['app-auth.spec.js'] },
    { name: 'auth-types', use: { browserName: 'chromium' }, testMatch: ['auth-types.spec.js'] },
    { name: 'auth-connector', use: { browserName: 'chromium' }, testMatch: ['auth-connector.spec.js'] },
    { name: 'admin', use: { browserName: 'chromium' }, testMatch: ['admin.spec.js'] },
    { name: 'cli-auth', use: { browserName: 'chromium' }, testMatch: ['cli-auth.spec.js'] },
    { name: 'grpc', use: { browserName: 'chromium' }, testMatch: ['grpc-support.spec.js'] },
    { name: 'flatbuffers', use: { browserName: 'chromium' }, testMatch: ['fbs-support.spec.js'] },
    { name: 'deploy', use: { browserName: 'chromium' }, testMatch: ['deploy.spec.js'] },
    { name: 'generate-spec', use: { browserName: 'chromium' }, testMatch: ['generate-spec.spec.js'] },
    { name: 'exclude-endpoint', use: { browserName: 'chromium' }, testMatch: ['exclude-endpoint.spec.js'] },
    { name: 'developer-portal', use: { browserName: 'chromium' }, testMatch: ['developer-portal.spec.js'] },
    { name: 'collections-auto-save', use: { browserName: 'chromium' }, testMatch: ['collections-auto-save.spec.js'] },
    { name: 'response-field-hide', use: { browserName: 'chromium' }, testMatch: ['response-field-hide.spec.js'] },
    { name: 'request-history', use: { browserName: 'chromium' }, testMatch: ['request-history.spec.js'] },
    { name: 'sidebar-toggle', use: { browserName: 'chromium' }, testMatch: ['sidebar-toggle.spec.js'] },
    // Cross-browser (CI only)
    ...(process.env.CI ? [
      { name: 'firefox', use: { browserName: 'firefox' }, testMatch: ['apiforge.spec.js'] },
      { name: 'webkit', use: { browserName: 'webkit' }, testMatch: ['apiforge.spec.js'] },
    ] : []),
  ],
});
