/**
 * APIForge OpenAPI generation - fromApp() approach
 * 
 * Migration from @nestjs/swagger:
 *   Before: SwaggerModule.createDocument(app, config)
 *   After:  DocumentGenerator.fromApp(app, config)
 *
 * That's it. Same NestJS app, same pattern.
 */
import 'reflect-metadata';
import { NestFactory } from '@nestjs/core';
import { DocumentGenerator } from '@apiforge/nestjs';
import { AppModule } from './apiforge-version/app.module';
import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

async function generate() {
  // Same as @nestjs/swagger: create app, init, generate doc
  const app = await NestFactory.create(AppModule, { logger: false });
  await app.init();

  const document = await DocumentGenerator.fromApp(app, {
    title: 'Petstore API (APIForge)',
    description: 'Generated by @apiforge/nestjs using fromApp()',
    version: '1.0.0',
    servers: [
      { url: 'http://localhost:3000', description: 'Local' },
      { url: 'https://api.petstore.example.com', description: 'Production' },
    ],
    bearerAuth: { name: 'JWT', scheme: 'bearer', bearerFormat: 'JWT' },
    tags: [
      { name: 'pets', description: 'Pet management' },
      { name: 'users', description: 'User management' },
    ],
  });

  const outDir = join(__dirname, '..', 'apiforge-docs');
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, 'openapi.json'), JSON.stringify(document, null, 2));

  console.log('Generated apiforge-docs/openapi.json');
  console.log('  Paths:', Object.keys(document.paths || {}).length);
  console.log('  Schemas:', Object.keys(document.components?.schemas || {}).length);
  console.log('  Tags:', document.tags?.map((t: any) => t.name));

  await app.close();
}

generate().catch(console.error);
